version: "3"
services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:3000
    privileged: true
    volumes:
      - ./advanced-AISpeculation:/app
    tty: true
    working_dir: /app
    stdin_open: true
